### ISSUE TITLE
Cleanest way of plotting columns of a matrix (or multiple functions)

### ISSUE THREAD

**Issue by juliohm** [dcjones/Gadfly.jl#529] opened 2015-01-16 05:10 UTC
I was not able to find an answer to this simple question in the docs. Let's say I have a matrix such that the first column has the abscissas in the x axis and the other columns are functions evaluated at these abscissas. How do I plot all columns at once in different color and with a legend?

Alternatively, suppose I have three functions:

```julia
x(n) = 2n
y1(n) = n+2
y2(n) = sin(n)
```

How do I plot `x vs. y1` and `x vs. y2` in different color with a legend varying n=1:10?

**Comment by aviks** [comment] 2015-01-16 13:44
duplicate of #526. 

Gadfly works best with stacked DataFrames, rather than two dimensional matrices. There is a workaround with layers as described in the above issue. But that is not perfect. The best way to do what you need, with the functions defined above, is to convert your data into a DataFrame. 

```julia
df=DataFrame(n=repeat([1:10], outer=[3]), 
            y=vcat([x(n) for n=1:10],[y1(n) for n=1:10], [y2(n) for n=1:10]), 
            fun=repeat(["x", "y1", "y2"], inner=[10]))
plot(df, color="fun", x="n", y="y", Geom.point, Geom.line)
```
![screen shot 2015-01-16 at 13 41 54](https://cloud.githubusercontent.com/assets/378918/5776901/810e30a0-9d85-11e4-857c-5f8eed98f996.png)

**Closed by aviks** 2015-01-16 13:44 UTC

**Comment by zhujinxuan** [comment] 2015-01-16 13:58
As I reply through my email app on my iPhone, I hadn't whether it is right in syntax.I highly recommend the function melt, you can do it this way.Using DataFramesT=[1:10]Df = DataFrame( x=2T, y1 = T+2, y2 = sin(T))Plot( melt(Df, :x) , x=:x , y=:value, color=:variable, Geom.line, Geom.point)Sent using CloudMagicOn Fri, Jan 16, 2015 at 21:44,  dcjones/Gadfly.jl <reply@reply.github.com> wrote:            duplicate of #526. 

Gadfly works best with stacked DataFrames, rather than two dimensional matrices. There is a workaround with layers as described in the above issue. But that is not perfect. The best way to do what you need, with the functions defined above, is to convert your data into a DataFrame. 

df=DataFrame(n=repeat([1:10], outer=[3]), 
            y=vcat([x(n) for n=1:10],[y1(n) for n=1:10], [y2(n) for n=1:10]), 
            fun=repeat(["x", "y1", "y2"], inner=[10]))
plot(df, color="fun", x="n", y="y", Geom.point, Geom.line)

**Comment by juliohm** [comment] 2015-01-16 18:29
I understood we don't have a clean call to achieve what I've asked with Gadfly. @aviks, why you closed the issue then?

**Comment by juliohm** [comment] 2015-01-16 18:55
The cleanest (methodical) solution I could come up with so far is:

```julia
df1 = DataFrame(x=1:10, y=f(1:10), label="f(x)")
df2 = DataFrame(x=1:10, y=g(1:10), label="g(x)")
# ...
df = vcat(df1, df2, ...)

plot(df, x=:x, y=:y, color=:label, Geom.line)
```

It doesn't require all those trick calls to `repeat()` and is extensible to multiple functions.

However, it would be nice to plot functions directly without this intermediate creation of dataframes.

**Comment by zhujinxuan** [comment] 2015-01-17 09:31
Sorry for my previous comment from my iPhone. The format was distoried and that message was unreadable. 

I recommend `melt` from package `DataFrames`.  It serves a near function of `vcat` but requires much less codes. For example:

```
using Gadfly
using DataFrames
T = [1:10.0]
df = DataFrame(x = 2*T, y1= T+2, y2= sin(T) )
plot(melt(df, :x), x = :x, y = :value, color = :variable, Geom.line, Geom.point )
```

**Comment by aviks** [comment] 2015-01-17 10:25
Hi @juliohm  Yes, there may not be clean way to do that, but I closed this issue because the same thing is being discussed in issue number #526 , which I'd linked to in my comment. Let me know if you disagree, and I'll re-open this. 

Thanks @zhujinxuan .

**Comment by juliohm** [comment] 2015-01-17 18:42
Thanks @aviks, it's okay to close this as duplicate.
