### ISSUE TITLE
BarPlot xmin and xmax don't work

### ISSUE THREAD

**Issue by benavoli** [dcjones/Gadfly.jl#758] opened 2015-12-02 11:12 UTC
using Gadfly
using DataFrames

df = DataFrame(
x=[1],
y=[0.1],    
xmin=[0.9],
xmax=[1.1]
)

plot(df, x=:x, y=:y,  xmin=:xmin, xmax=:xmax, Geom.bar)

The width of the bars does not change

**Comment by JohnHBrock** [comment] 2016-05-04 04:41
I'm able to reproduce this using Gadfly v4.2.

```julia
using Gadfly
Gadfly.plot(xmin=[0,2,4,6],
            xmax=[2,4,5,8],
            y=[4,2,7,1],
            Geom.bar
            )
```

**Comment by JohnHBrock** [comment] 2016-05-05 00:37
It looks like the problem is in the BarStatistic variant of apply_statistic: https://github.com/dcjones/Gadfly.jl/blob/fdb02ed4d5a8579d46a9d65ea9edac2b757c839e/src/statistics.jl#L200

`barminmax` produces new values for the bar boundaries, which overwrite the `xmin` and `xmax` values.

**Comment by tlnagy** [comment] 2016-09-01 23:19
This is fixed on master thanks to @JohnHBrock's sleuthing.

**Closed** 2016-09-01 23:19 UTC
