### ISSUE TITLE
Log scale with Geom.contour

### ISSUE THREAD

**Issue by rand5** [dcjones/Gadfly.jl#862] opened 2016-07-08 18:22 UTC
Is having a log scale compatible with Geom.contour?
I have a line
`plot(z=z, x=X, y=Y,Geom.contour)`
that executes perfectly fine, but when I do 
`plot(z=z, x=X, y=Y,Geom.contour,Scale.y_log10)`
I get the error,

> DomainError:
log10 will only return a complex result if called with a complex argument. Try log10(complex(x)).
in log10 at math.jl:137

I have checked and all of my X and Y values are strictly positive.

**Comment by tlnagy** [comment] 2016-08-22 00:57
Sorry for the delay, but this works for me.

```julia
plot(z=(x,y) -> x*exp(-(x-round(Int, x))^2-y^2),
            x=linspace(-8,8,150), y=linspace(1,2,150), Geom.contour, Scale.y_log10)
```

Do you have a minimal example?

**Comment by tlnagy** [comment] 2016-09-01 04:31
I'm going to close this since I can't reproduce. Please reopen this if you run into this again.

**Closed by tlnagy** 2016-09-01 04:31 UTC
